server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: zone-service
              uri: lb://zone-service
              predicates:
                - Path=/zone-service/**
              filters:
                - StripPrefix=1

            - id: sensor-service
              uri: lb://sensor-service
              predicates:
                - Path=/sensor-service/**
              filters:
                - StripPrefix=1

            - id: automation-service
              uri: lb://automation-service
              predicates:
                - Path=/automation-service/**
              filters:
                - StripPrefix=1

            - id: crop-service
              uri: lb://crop-service
              predicates:
                - Path=/crop-service/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
