server:
  port: 8083

spring:
  application:
    name: automation-service

services:
  zone-service:
    url: http://localhost:8081/api/v1/zones

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true