server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecosync_crop_db?createDatabaseIfNotExist=true
    username: postgres
    password: Sachintha@2003
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true