server:
  port: 8082

spring:
  application:
    name: sensor-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecosync_sensor_db

iot:
  provider:
    url: http://localhost:9090/api
    username: "sachintha_p"
    password: "12345678"

automation:
  service:
    url: http://localhost:8083/api/automation/process

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}